from setuptools import setup, find_packages

setup(
    name="SimDLL",
    version="0.1.0",
    author="Shuvangkar Das",
    author_email="shuvangkarcdas@gmail.com",
    description="Python wrapper to read DLL files generated by Simulink",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/shuvangkardas/SimDLL",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
